[tool.poetry]
name = "coh2stats"
version = "0.1.0"
description = ""
authors = ["George Zed <georlema@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.6"
aiohttp = "1.2.0"
appdirs = "1.4.3"
async-timeout = "3.0.0"
certifi = "2019.6.16"
chardet = "3.0.4"
click = "6.7"
facebook-sdk = "3.1.0"
flask = "1.0.2"
greenlet = "0.4.15"
gunicorn = "19.9.0"
h11 = "0.8.1"
h2 = "3.1.1"
hpack = "3.0.0"
httpx = "0.6.8"
huey = "2.1.0"
hyperframe = "5.2.0"
idna = "2.7"
itsdangerous = "0.24"
jinja2 = "2.10"
markupsafe = "1.0"
meinheld = "1.0.1"
multidict = "4.3.1"
pyee = "6.0.0"
pymongo = "3.7.0"
pyppeteer = "0.0.25"
requests = "2.22.0"
rfc3986 = "1.3.2"
tqdm = "4.32.2"
urllib3 = "1.25.3"
websockets = "8.0.2"
werkzeug = "0.14.1"
yarl = "1.2.6"

[tool.poetry.dev-dependencies]
autopep8 = "1.4.4"
backcall = "0.1.0"
decorator = "4.4.1"
entrypoints = "0.3"
flake8 = "3.7.9"
ipdb = "0.12.2"
ipython-genutils = "0.2.0"
ipython = "7.9.0"
jedi = "0.15.1"
mccabe = "0.6.1"
parso = "0.5.1"
pexpect = "4.7.0"
pickleshare = "0.7.5"
prompt-toolkit = "2.0.10"
ptyprocess = "0.6.0"
pycodestyle = "2.5.0"
pyflakes = "2.1.1"
pygments = "2.4.2"
six = "1.13.0"
traitlets = "4.3.3"
wcwidth = "0.1.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
