[tool.poetry]
name = "coh2stats"
version = "0.1.0"
description = ""
authors = ["George Zed <georlema@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.6"
facebook-sdk = "3.1.0"
flask = "1.0.2"
gunicorn = "19.9.0"
httpx = "0.7.5"
huey = "2.1.3"
meinheld = "1.0.1"
pymongo = "3.7.0"
pyppeteer = "0.0.25"
requests = "2.22.0"

[tool.poetry.dev-dependencies]
autopep8 = "1.4.4"
backcall = "0.1.0"
decorator = "4.4.1"
entrypoints = "0.3"
flake8 = "3.7.9"
ipdb = "0.12.2"
ipython-genutils = "0.2.0"
ipython = "7.9.0"
jedi = "0.15.1"
mccabe = "0.6.1"
parso = "0.5.1"
pexpect = "4.7.0"
pickleshare = "0.7.5"
prompt-toolkit = "2.0.10"
ptyprocess = "0.6.0"
pycodestyle = "2.5.0"
pyflakes = "2.1.1"
pygments = "2.4.2"
six = "1.13.0"
traitlets = "4.3.3"
wcwidth = "0.1.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
